apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: nginx-nfs-pvc
              mountPath: /usr/share/nginx/html/data-nfs
            - name: nginx-longhorn-pvc
              mountPath: /usr/share/nginx/html/data-longhorn
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: index.html
                path: index.html
        - name: nginx-nfs-pvc
          persistentVolumeClaim:
            claimName: nginx-nfs-pvc
        - name: nginx-longhorn-pvc
          persistentVolumeClaim:
            claimName: nginx-longhorn-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
    - name: http
      port: 443
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - anhhm.kbuor.tech
      secretName: nginx-tls
  rules:
    - host: anhhm.kbuor.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 443
